# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

variable "aws_bucket_vault_license_arn" {
  type        = string
  description = "ARN of S3 bucket with Vault license"
}

variable "aws_region" {
  type        = string
  description = "Specific AWS region being used"
}

variable "kms_key_arn" {
  type        = string
  description = "KMS Key ARN used for Vault auto-unseal permissions"
}

variable "permissions_boundary" {
  description = "(Optional) IAM Managed Policy to serve as permissions boundary for IAM Role"
  type        = string
  default     = null
}

variable "resource_name_prefix" {
  type        = string
  description = "Resource name prefix used for tagging and naming AWS resources"
}

variable "secrets_manager_arn" {
  type        = string
  description = "Secrets manager ARN where TLS cert info is stored"
}

#variable "vault_agent_auto_auth_arn" {
#  type        = string
#  description = "Vault agent auto_auth"
#}

variable "aws_vault_iam_role_arn" {
  type        = string
  default     = null
  description = "IAM Role ARN, for AWS Auto-Auth"
}

variable "user_supplied_iam_role_name" {
  type        = string
  description = "(OPTIONAL) User-provided IAM role name. This will be used for the instance profile provided to the AWS launch configuration. The minimum permissions must match the defaults generated by the IAM submodule for cloud auto-join and auto-unseal."
  default     = null
}
